### ISSUE TITLE
JVM missing issue

### ISSUE THREAD

**Issue by avitaliano** [ninrod/dotfiles#120]
Filipe,
recebo a mensagem abaixo toda vez que inicio uma sessão no iterm

> Unable to find any JVMs matching version "1.7".

Essa mensagem rolou também ao instalar via 
> install.zsh

Tenho JVM 1.8 instalada no mac.

**Comment by ninrod** [comment]
fala @avitaliano 

em que commit vc está? 

```sh
git branch -v
```

**Comment by avitaliano** [comment]
Fiz fork novamente hoje... Provavelmente no último...

* master 699ceb2 xfce4-term: unlimited scroll

abs,

**Comment by ninrod** [comment]
Hum, então o problema deve estar [aqui](https://github.com/ninrod/dotfiles/blob/7ec9b385d6351a640572bc4b0cdec7b076dca170/options/osx/exports.zsh#L17-L22). tenta comentar essas linhas. o problema deve sumir.

tem que comentar [essa](https://github.com/ninrod/dotfiles/blob/7ec9b385d6351a640572bc4b0cdec7b076dca170/options/osx/exports.zsh#L28) linha também.

**Comment by avitaliano** [comment]
exato!

done

Em qui, 7 de set de 2017 às 21:29, Filipe Silva <notifications@github.com>
escreveu:

**Comment by ninrod** [comment]
blz!
