### ISSUE TITLE
Use built-in colors utility instead of termcolors.zsh

### ISSUE THREAD

**Issue by kutsan** [ninrod/dotfiles#134]
Instead of doing [this](https://github.com/ninrod/dotfiles/blob/aed698eb285eba7d8223c165c77b4099f603b1cb/zsh/termcolors.zsh) you can do this:

```sh
autoload -U colors
colors
```

and use it like that:

```sh
echo "${fg[yellow]}  Example text.  ${reset_color}"
echo "${fg_bold[yellow]}  Example text.  ${reset_color}"
echo "${bg_bold[yellow]}  Example text.  ${reset_color} ${bg[yellow]}${bg_bold[black]} Another text. ${reset_color}"
```

![image](https://user-images.githubusercontent.com/10108377/40678975-983c0328-638a-11e8-9ae4-d79459d91342.png)

And more info https://github.com/zsh-users/zsh/blob/master/Functions/Misc/colors.

**Comment by ninrod** [comment]
very interesting. this is provided by the zsh-users plugin, right?

**Comment by kutsan** [comment]
This comes with zsh itself, it's built-in. You don't need to install any plugin.

**Comment by ninrod** [comment]
it's very clean. But I'll have to find all the places where I use the old form. shouldn't be too hard.

**Comment by kutsan** [comment]
I mean, actually both ways are fine. You don't need to change your setup or anything. If you want to keep it simple, continue using your `termcolors.zsh`. Just know that `colors` utility exists.
