### ISSUE TITLE
verify bspwm scratchpad and tdrop

### ISSUE THREAD

**Issue by ninrod** [ninrod/dotfiles#99]
https://wiki.archlinux.org/index.php/Bspwm#Scratchpad

**Comment by noctuid** [comment]
Have you seen [tdrop](https://github.com/noctuid/tdrop)?

**Comment by ninrod** [comment]
Hi @noctuid! no, I have not. Is this an alternative solution to scratchpad? will check that out!

**Comment by noctuid** [comment]
It's basically the same with a lot more features (and it is cross-wm). If there is anything you want, feel free to make an issue.

**Comment by ninrod** [comment]
I use an emacs' scratch buffer all the time for scratches. it can be called from virtually anywhere because I run emacs as a daemon so problem solved!
